-- -------------------------------------------------------------
-- 
-- File Name: /home/vinicius.ls/PSD1/A2/filtro2/projeto_hdl/hdlsrc/filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits_pkg.vhd
-- Created: 2019-07-06 23:28:09
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Filtro_FIR_HP_8bits_pkg IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
END Filtro_FIR_HP_8bits_pkg;

