open_system('filtro2_fir_sim_r2015a');
open_system('gm_filtro2_fir_sim_r2015a');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits/filter', 'user2');
annotate_port('gm_filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits/filter', 1, 1, 'Block not characterized');
hilite_system('filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits/filter', 'user2');
annotate_port('filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits/filter', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits/filter', 'user2');
annotate_port('gm_filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits/filter', 1, 1, 'Block not characterized');
hilite_system('filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits/filter', 'user2');
annotate_port('filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits/filter', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
