-- -------------------------------------------------------------
-- 
-- File Name: /home/vinicius.ls/PSD1/A2/filtro3/projeto_hdl/hdlsrc/filtro3_iir_sim_r2015a/Filtro_IIR_BP_20bits_unsigned.vhd
-- Created: 2019-07-09 01:42:03
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.0001
-- Target subsystem base rate: 0.0001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out_rsvd                      ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Filtro_IIR_BP_20bits_unsigned
-- Source Path: filtro3_iir_sim_r2015a/Filtro_IIR_BP_20bits_unsigned
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Filtro_IIR_BP_20bits_unsigned IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In_rsvd                           :   IN    real;  -- double
        ce_out                            :   OUT   std_logic;
        Out_rsvd                          :   OUT   real  -- double
        );
END Filtro_IIR_BP_20bits_unsigned;


ARCHITECTURE rtl OF Filtro_IIR_BP_20bits_unsigned IS

  -- Component Declarations
  COMPONENT filter
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          filter_in                       :   IN    real;  -- double
          filter_out                      :   OUT   real  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : filter
    USE ENTITY work.filter(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL filter_out1                      : real := 0.0;  -- double

BEGIN
  -- <S3>/filter
  u_filter : filter
    PORT MAP( clk => clk,
              enb => enb,
              reset => reset,
              filter_in => In_rsvd,  -- double
              filter_out => filter_out1  -- double
              );

  enb <= clk_enable;

  ce_out <= clk_enable;

  Out_rsvd <= filter_out1;

END rtl;

