-- -------------------------------------------------------------
-- 
-- File Name: /home/vinicius.ls/PSD1/A2/filtro2/projeto_hdl/hdlsrc/filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits.vhd
-- Created: 2019-07-06 23:28:09
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.0001
-- Target subsystem base rate: 0.0001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out_rsvd                      ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Filtro_FIR_HP_8bits
-- Source Path: filtro2_fir_sim_r2015a/Filtro_FIR_HP_8bits
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Filtro_FIR_HP_8bits IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In_rsvd                           :   IN    std_logic_vector(24 DOWNTO 0);  -- sfix25_En23
        ce_out                            :   OUT   std_logic;
        Out_rsvd                          :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
        );
END Filtro_FIR_HP_8bits;


ARCHITECTURE rtl OF Filtro_FIR_HP_8bits IS

  -- Component Declarations
  COMPONENT filter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          filter_in                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          filter_out                      :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En23
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : filter
    USE ENTITY work.filter(rtl);

  -- Signals
  SIGNAL In_signed                        : signed(24 DOWNTO 0);  -- sfix25_En23
  SIGNAL Input_Quantizer_out1             : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL filter_out1                      : std_logic_vector(24 DOWNTO 0);  -- ufix25

BEGIN
  -- <S2>/filter
  u_filter : filter
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              filter_in => std_logic_vector(Input_Quantizer_out1),  -- sfix16_En15
              filter_out => filter_out1  -- sfix25_En23
              );

  In_signed <= signed(In_rsvd);

  -- <S2>/Input Quantizer
  
  Input_Quantizer_out1 <= X"7FFF" WHEN ((In_signed(24) = '0') AND (In_signed(23) /= '0')) OR ((In_signed(24) = '0') AND (In_signed(23 DOWNTO 8) = X"7FFF")) ELSE
      X"8000" WHEN (In_signed(24) = '1') AND (In_signed(23) /= '1') ELSE
      In_signed(23 DOWNTO 8) + ('0' & (In_signed(7) AND (( NOT In_signed(24)) OR (In_signed(6) OR In_signed(5) OR In_signed(4) OR In_signed(3) OR In_signed(2) OR In_signed(1) OR In_signed(0)))));

  ce_out <= clk_enable;

  Out_rsvd <= filter_out1;

END rtl;

