-- ------------------------------------------------------------
-- 
-- File Name: /home/vinicius.ls/PSD1/A2/filtro3/projeto_hdl/hdlsrc/filtro3_iir_sim_r2015a/filter
-- Created: 2019-07-07 00:34:38
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- ------------------------------------------------------------
-- 
-- 
-- ------------------------------------------------------------
-- 
-- Module: filter
-- Source Path: /filter
-- 
-- ------------------------------------------------------------
-- 
-- HDL Implementation    : Fully parallel
-- Multipliers           : 13
-- Folding Factor        : 1


LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         enb                             :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(15 DOWNTO 0); -- sfix16_En15
         filter_out                      :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16_En15
  -- Constants
  CONSTANT scaleconst1                    : signed(19 DOWNTO 0) := to_signed(286288, 20); -- sfix20_En25
  CONSTANT coeff_b1_section1              : signed(19 DOWNTO 0) := to_signed(262144, 20); -- sfix20_En18
  CONSTANT coeff_b2_section1              : signed(19 DOWNTO 0) := to_signed(92630, 20); -- sfix20_En18
  CONSTANT coeff_b3_section1              : signed(19 DOWNTO 0) := to_signed(262144, 20); -- sfix20_En18
  CONSTANT coeff_a2_section1              : signed(19 DOWNTO 0) := to_signed(213692, 20); -- sfix20_En18
  CONSTANT coeff_a3_section1              : signed(19 DOWNTO 0) := to_signed(221542, 20); -- sfix20_En18
  CONSTANT coeff_b1_section2              : signed(19 DOWNTO 0) := to_signed(262144, 20); -- sfix20_En18
  CONSTANT coeff_b2_section2              : signed(19 DOWNTO 0) := to_signed(368877, 20); -- sfix20_En18
  CONSTANT coeff_b3_section2              : signed(19 DOWNTO 0) := to_signed(262144, 20); -- sfix20_En18
  CONSTANT coeff_a2_section2              : signed(19 DOWNTO 0) := to_signed(253027, 20); -- sfix20_En18
  CONSTANT coeff_a3_section2              : signed(19 DOWNTO 0) := to_signed(222721, 20); -- sfix20_En18
  CONSTANT coeff_b1_section3              : signed(19 DOWNTO 0) := to_signed(262144, 20); -- sfix20_En18
  CONSTANT coeff_b2_section3              : signed(19 DOWNTO 0) := to_signed(190191, 20); -- sfix20_En18
  CONSTANT coeff_b3_section3              : signed(19 DOWNTO 0) := to_signed(262144, 20); -- sfix20_En18
  CONSTANT coeff_a2_section3              : signed(19 DOWNTO 0) := to_signed(213038, 20); -- sfix20_En18
  CONSTANT coeff_a3_section3              : signed(19 DOWNTO 0) := to_signed(250144, 20); -- sfix20_En18
  CONSTANT coeff_b1_section4              : signed(19 DOWNTO 0) := to_signed(262144, 20); -- sfix20_En18
  CONSTANT coeff_b2_section4              : signed(19 DOWNTO 0) := to_signed(307758, 20); -- sfix20_En18
  CONSTANT coeff_b3_section4              : signed(19 DOWNTO 0) := to_signed(262144, 20); -- sfix20_En18
  CONSTANT coeff_a2_section4              : signed(19 DOWNTO 0) := to_signed(279498, 20); -- sfix20_En18
  CONSTANT coeff_a3_section4              : signed(19 DOWNTO 0) := to_signed(251506, 20); -- sfix20_En18
  -- Signals
  SIGNAL input_typeconvert                : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL scale1                           : signed(39 DOWNTO 0); -- sfix40_En40
  SIGNAL mul_temp                         : signed(35 DOWNTO 0); -- sfix36_En40
  SIGNAL scaletypeconvert1                : signed(15 DOWNTO 0); -- sfix16_En16
  -- Section 1 Signals 
  SIGNAL a1sum1                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL a2sum1                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL b1sum1                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL b2sum1                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL typeconvert1                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section1                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv1                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL a2mul1                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL a3mul1                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b1mul1                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b2mul1                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b3mul1                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sub_cast                         : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_cast_1                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_temp                         : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL sub_cast_2                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_cast_3                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_temp_1                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL b1multypeconvert1                : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast                         : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_1                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_temp                         : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL add_cast_2                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_3                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_temp_1                       : signed(40 DOWNTO 0); -- sfix41_En33
  -- Section 2 Signals 
  SIGNAL a1sum2                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL a2sum2                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL b1sum2                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL b2sum2                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL typeconvert2                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section2                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv2                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL a2mul2                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL a3mul2                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b1mul2                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b2mul2                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b3mul2                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sub_cast_4                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_cast_5                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_temp_2                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL sub_cast_6                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_cast_7                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_temp_3                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL b1multypeconvert2                : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_4                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_5                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_temp_2                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL add_cast_6                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_7                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_temp_3                       : signed(40 DOWNTO 0); -- sfix41_En33
  -- Section 3 Signals 
  SIGNAL a1sum3                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL a2sum3                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL b1sum3                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL b2sum3                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL typeconvert3                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section3                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv3                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL a2mul3                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL a3mul3                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b1mul3                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b2mul3                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b3mul3                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sub_cast_8                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_cast_9                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_temp_4                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL sub_cast_10                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_cast_11                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_temp_5                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL b1multypeconvert3                : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_8                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_9                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_temp_4                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL add_cast_10                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_11                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_temp_5                       : signed(40 DOWNTO 0); -- sfix41_En33
  -- Section 4 Signals 
  SIGNAL a1sum4                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL a2sum4                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL b1sum4                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL b2sum4                           : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL typeconvert4                     : signed(15 DOWNTO 0); -- sfix16_En15
  SIGNAL delay_section4                   : delay_pipeline_type(0 TO 1); -- sfix16_En15
  SIGNAL inputconv4                       : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL a2mul4                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL a3mul4                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b1mul4                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b2mul4                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL b3mul4                           : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sub_cast_12                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_cast_13                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_temp_6                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL sub_cast_14                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_cast_15                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL sub_temp_7                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL b1multypeconvert4                : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_12                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_13                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_temp_6                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL add_cast_14                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_cast_15                      : signed(39 DOWNTO 0); -- sfix40_En33
  SIGNAL add_temp_7                       : signed(40 DOWNTO 0); -- sfix41_En33
  SIGNAL output_typeconvert               : signed(15 DOWNTO 0); -- sfix16_En11


BEGIN

  -- Block Statements
  input_typeconvert <= signed(filter_in);

  mul_temp <= input_typeconvert * scaleconst1;
  scale1 <= resize(mul_temp, 40);

  scaletypeconvert1 <= resize(shift_right(scale1(39 DOWNTO 0) + ( "0" & (scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24) & NOT scale1(24))), 24), 16);

  --   ------------------ Section 1 ------------------

  typeconvert1 <= resize(shift_right(a1sum1(33 DOWNTO 0) + ( "0" & (a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18) & NOT a1sum1(18))), 18), 16);

  delay_process_section1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section1 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        delay_section1(1) <= delay_section1(0);
        delay_section1(0) <= typeconvert1;
      END IF;
    END IF;
  END PROCESS delay_process_section1;

  inputconv1 <= resize(scaletypeconvert1(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 40);

  a2mul1 <= delay_section1(0) * coeff_a2_section1;

  a3mul1 <= delay_section1(1) * coeff_a3_section1;

  b1mul1 <= resize(typeconvert1(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 36);

  b2mul1 <= delay_section1(0) * coeff_b2_section1;

  b3mul1 <= resize(delay_section1(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 36);

  sub_cast <= inputconv1;
  sub_cast_1 <= resize(a2mul1, 40);
  sub_temp <= resize(sub_cast, 41) - resize(sub_cast_1, 41);
  a2sum1 <= sub_temp(39 DOWNTO 0);

  sub_cast_2 <= a2sum1;
  sub_cast_3 <= resize(a3mul1, 40);
  sub_temp_1 <= resize(sub_cast_2, 41) - resize(sub_cast_3, 41);
  a1sum1 <= sub_temp_1(39 DOWNTO 0);

  b1multypeconvert1 <= resize(b1mul1, 40);

  add_cast <= b1multypeconvert1;
  add_cast_1 <= resize(b2mul1, 40);
  add_temp <= resize(add_cast, 41) + resize(add_cast_1, 41);
  b2sum1 <= add_temp(39 DOWNTO 0);

  add_cast_2 <= b2sum1;
  add_cast_3 <= resize(b3mul1, 40);
  add_temp_1 <= resize(add_cast_2, 41) + resize(add_cast_3, 41);
  b1sum1 <= add_temp_1(39 DOWNTO 0);

  --   ------------------ Section 2 ------------------

  typeconvert2 <= resize(shift_right(a1sum2(33 DOWNTO 0) + ( "0" & (a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18) & NOT a1sum2(18))), 18), 16);

  delay_process_section2 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section2 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        delay_section2(1) <= delay_section2(0);
        delay_section2(0) <= typeconvert2;
      END IF;
    END IF;
  END PROCESS delay_process_section2;

  inputconv2 <= b1sum1;

  a2mul2 <= delay_section2(0) * coeff_a2_section2;

  a3mul2 <= delay_section2(1) * coeff_a3_section2;

  b1mul2 <= resize(typeconvert2(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 36);

  b2mul2 <= delay_section2(0) * coeff_b2_section2;

  b3mul2 <= resize(delay_section2(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 36);

  sub_cast_4 <= inputconv2;
  sub_cast_5 <= resize(a2mul2, 40);
  sub_temp_2 <= resize(sub_cast_4, 41) - resize(sub_cast_5, 41);
  a2sum2 <= sub_temp_2(39 DOWNTO 0);

  sub_cast_6 <= a2sum2;
  sub_cast_7 <= resize(a3mul2, 40);
  sub_temp_3 <= resize(sub_cast_6, 41) - resize(sub_cast_7, 41);
  a1sum2 <= sub_temp_3(39 DOWNTO 0);

  b1multypeconvert2 <= resize(b1mul2, 40);

  add_cast_4 <= b1multypeconvert2;
  add_cast_5 <= resize(b2mul2, 40);
  add_temp_2 <= resize(add_cast_4, 41) + resize(add_cast_5, 41);
  b2sum2 <= add_temp_2(39 DOWNTO 0);

  add_cast_6 <= b2sum2;
  add_cast_7 <= resize(b3mul2, 40);
  add_temp_3 <= resize(add_cast_6, 41) + resize(add_cast_7, 41);
  b1sum2 <= add_temp_3(39 DOWNTO 0);

  --   ------------------ Section 3 ------------------

  typeconvert3 <= resize(shift_right(a1sum3(33 DOWNTO 0) + ( "0" & (a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18) & NOT a1sum3(18))), 18), 16);

  delay_process_section3 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section3 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        delay_section3(1) <= delay_section3(0);
        delay_section3(0) <= typeconvert3;
      END IF;
    END IF;
  END PROCESS delay_process_section3;

  inputconv3 <= b1sum2;

  a2mul3 <= delay_section3(0) * coeff_a2_section3;

  a3mul3 <= delay_section3(1) * coeff_a3_section3;

  b1mul3 <= resize(typeconvert3(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 36);

  b2mul3 <= delay_section3(0) * coeff_b2_section3;

  b3mul3 <= resize(delay_section3(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 36);

  sub_cast_8 <= inputconv3;
  sub_cast_9 <= resize(a2mul3, 40);
  sub_temp_4 <= resize(sub_cast_8, 41) - resize(sub_cast_9, 41);
  a2sum3 <= sub_temp_4(39 DOWNTO 0);

  sub_cast_10 <= a2sum3;
  sub_cast_11 <= resize(a3mul3, 40);
  sub_temp_5 <= resize(sub_cast_10, 41) - resize(sub_cast_11, 41);
  a1sum3 <= sub_temp_5(39 DOWNTO 0);

  b1multypeconvert3 <= resize(b1mul3, 40);

  add_cast_8 <= b1multypeconvert3;
  add_cast_9 <= resize(b2mul3, 40);
  add_temp_4 <= resize(add_cast_8, 41) + resize(add_cast_9, 41);
  b2sum3 <= add_temp_4(39 DOWNTO 0);

  add_cast_10 <= b2sum3;
  add_cast_11 <= resize(b3mul3, 40);
  add_temp_5 <= resize(add_cast_10, 41) + resize(add_cast_11, 41);
  b1sum3 <= add_temp_5(39 DOWNTO 0);

  --   ------------------ Section 4 ------------------

  typeconvert4 <= resize(shift_right(a1sum4(33 DOWNTO 0) + ( "0" & (a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18) & NOT a1sum4(18))), 18), 16);

  delay_process_section4 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_section4 <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        delay_section4(1) <= delay_section4(0);
        delay_section4(0) <= typeconvert4;
      END IF;
    END IF;
  END PROCESS delay_process_section4;

  inputconv4 <= b1sum3;

  a2mul4 <= delay_section4(0) * coeff_a2_section4;

  a3mul4 <= delay_section4(1) * coeff_a3_section4;

  b1mul4 <= resize(typeconvert4(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 36);

  b2mul4 <= delay_section4(0) * coeff_b2_section4;

  b3mul4 <= resize(delay_section4(1)(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 36);

  sub_cast_12 <= inputconv4;
  sub_cast_13 <= resize(a2mul4, 40);
  sub_temp_6 <= resize(sub_cast_12, 41) - resize(sub_cast_13, 41);
  a2sum4 <= sub_temp_6(39 DOWNTO 0);

  sub_cast_14 <= a2sum4;
  sub_cast_15 <= resize(a3mul4, 40);
  sub_temp_7 <= resize(sub_cast_14, 41) - resize(sub_cast_15, 41);
  a1sum4 <= sub_temp_7(39 DOWNTO 0);

  b1multypeconvert4 <= resize(b1mul4, 40);

  add_cast_12 <= b1multypeconvert4;
  add_cast_13 <= resize(b2mul4, 40);
  add_temp_6 <= resize(add_cast_12, 41) + resize(add_cast_13, 41);
  b2sum4 <= add_temp_6(39 DOWNTO 0);

  add_cast_14 <= b2sum4;
  add_cast_15 <= resize(b3mul4, 40);
  add_temp_7 <= resize(add_cast_14, 41) + resize(add_cast_15, 41);
  b1sum4 <= add_temp_7(39 DOWNTO 0);

  output_typeconvert <= resize(shift_right(b1sum4(37 DOWNTO 0) + ( "0" & (b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22) & NOT b1sum4(22))), 22), 16);

  -- Assignment Statements
  filter_out <= std_logic_vector(output_typeconvert);
END rtl;
