-- -------------------------------------------------------------
-- 
-- File Name: /home/vinicius.ls/PSD1/A2/filtro3/projeto_hdl/hdlsrc/filtro3_iir_sim_r2015a/Filtro_IIR_BP_20bits_signed.vhd
-- Created: 2019-07-07 00:34:40
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.0001
-- Target subsystem base rate: 0.0001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out_rsvd                      ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Filtro_IIR_BP_20bits_signed
-- Source Path: filtro3_iir_sim_r2015a/Filtro_IIR_BP_20bits_signed
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Filtro_IIR_BP_20bits_signed IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In_rsvd                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        ce_out                            :   OUT   std_logic;
        Out_rsvd                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
        );
END Filtro_IIR_BP_20bits_signed;


ARCHITECTURE rtl OF Filtro_IIR_BP_20bits_signed IS

  -- Component Declarations
  COMPONENT filter
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          filter_in                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          filter_out                      :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En11
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : filter
    USE ENTITY work.filter(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In_signed                        : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Input_Quantizer_out1             : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL Input_Quantizer_out1_1           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL filter_out1                      : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  -- <S1>/filter
  u_filter : filter
    PORT MAP( clk => clk,
              enb => enb,
              reset => reset,
              filter_in => Input_Quantizer_out1_1,  -- sfix16_En15
              filter_out => filter_out1  -- sfix16_En11
              );

  In_signed <= signed(In_rsvd);

  -- <S1>/Input Quantizer
  
  Input_Quantizer_out1 <= X"7FFF" WHEN (In_signed(15) = '0') AND (In_signed(14 DOWNTO 11) /= "0000") ELSE
      X"8000" WHEN (In_signed(15) = '1') AND (In_signed(14 DOWNTO 11) /= "1111") ELSE
      In_signed(11 DOWNTO 0) & '0' & '0' & '0' & '0';

  Input_Quantizer_out1_1 <= std_logic_vector(Input_Quantizer_out1);

  enb <= clk_enable;

  ce_out <= clk_enable;

  Out_rsvd <= filter_out1;

END rtl;

