-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/simulink_with_hdl/C1.vhd
-- Created: 2019-06-28 14:37:04
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: C1
-- Source Path: simulink_with_hdl/P1/C1
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY C1 IS
  PORT( InC1_1                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        InC1_2                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        OutC1_1                           :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En28
        );
END C1;


ARCHITECTURE rtl OF C1 IS

  -- Signals
  SIGNAL InC1_1_signed                    : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL InC1_2_signed                    : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL Add1_add_cast                    : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL Add1_add_cast_1                  : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL Add1_out1                        : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL Gain1_out1                       : signed(33 DOWNTO 0);  -- sfix34_En28

BEGIN
  InC1_1_signed <= signed(InC1_1);

  InC1_2_signed <= signed(InC1_2);

  Add1_add_cast <= resize(InC1_1_signed, 17);
  Add1_add_cast_1 <= resize(InC1_2_signed, 17);
  Add1_out1 <= Add1_add_cast + Add1_add_cast_1;

  Gain1_out1 <= to_signed(16#0A000#, 17) * Add1_out1;

  OutC1_1 <= std_logic_vector(Gain1_out1);

END rtl;

