-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/simulink_with_hdl/DUT.vhd
-- Created: 2019-07-03 14:41:46
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.000125
-- Target subsystem base rate: 0.000125
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ceout         0.000125
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ceout         0.000125
-- Out2                          ceout         0.000125
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DUT
-- Source Path: simulink_with_hdl/DUT
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DUT IS
  PORT( clk                               :   IN    std_logic;
        resetx                            :   IN    std_logic;
        clkenable                         :   IN    std_logic;
        In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        ceout                             :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(33 DOWNTO 0);  -- sfix34_En29
        Out2                              :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En27
        );
END DUT;


ARCHITECTURE rtl OF DUT IS

  -- Component Declarations
  COMPONENT P1
    PORT( clk                             :   IN    std_logic;
          resetx                          :   IN    std_logic;
          enb                             :   IN    std_logic;
          InP1_1                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          Out_P1_1                        :   OUT   std_logic_vector(33 DOWNTO 0);  -- sfix34_En29
          Out_P1_2                        :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En27
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : P1
    USE ENTITY work.P1(rtl);

  -- Signals
  SIGNAL DC_sin_500                       : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL sin_500_sin_800                  : std_logic_vector(33 DOWNTO 0);  -- ufix34

BEGIN
  UP1_1 : P1
    PORT MAP( clk => clk,
              resetx => resetx,
              enb => clkenable,
              InP1_1 => In1,  -- sfix16_En15
              Out_P1_1 => DC_sin_500,  -- sfix34_En29
              Out_P1_2 => sin_500_sin_800  -- sfix34_En27
              );

  ceout <= clkenable;

  Out1 <= DC_sin_500;

  Out2 <= sin_500_sin_800;

END rtl;

