-- -------------------------------------------------------------
--
-- Module: P1_tb_data
-- Path: hdl_prj/hdlsrc/simulink_with_hdl
-- Created: 2019-07-03 13:50:08
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- Description: test bench data package
--
--
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;
USE work.P1_tb_pkg.ALL;

PACKAGE P1_tb_data IS


END P1_tb_data;

PACKAGE BODY P1_tb_data IS

END P1_tb_data;
