-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/simulink_with_hdl/simulink_with_hdl.vhd
-- Created: 2019-06-28 14:37:05
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.000125
-- Target subsystem base rate: 0.000125
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: simulink_with_hdl
-- Source Path: simulink_with_hdl
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY simulink_with_hdl IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic
        );
END simulink_with_hdl;


ARCHITECTURE rtl OF simulink_with_hdl IS

  -- Component Declarations
  COMPONENT P1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Out_P1_1                        :   OUT   std_logic_vector(33 DOWNTO 0);  -- sfix34_En28
          Out_P1_2                        :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En28
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : P1
    USE ENTITY work.P1(rtl);

  -- Signals
  SIGNAL DC_sin_500                       : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL sin_500_sin_800                  : std_logic_vector(33 DOWNTO 0);  -- ufix34

BEGIN
  u_P1 : P1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Out_P1_1 => DC_sin_500,  -- sfix34_En28
              Out_P1_2 => sin_500_sin_800  -- sfix34_En28
              );


END rtl;

